# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  default:
    - step:
        name: New ruby
        image: ruby:2.4.1
        script:
          - sed -i "s/'sqlite3'/'sqlite3', '~> 1.3.6'/g" redmine_crm.gemspec
          - sed -i "s/'mysql2'/'mysql2', '~> 0.4.0'/g" redmine_crm.gemspec
          - sed -i "s/'rubyzip'/'rubyzip'\n  spec.add_runtime_dependency 'loofah', '~>2.19.1'/g" redmine_crm.gemspec
          - bundle install
          - bundle exec rake test DB=sqlite
          - bundle exec rake test DB=postgresql
          - bundle exec rake test DB=mysql
        services:
          - mysql
          - postgres

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: redmine_crm_test
        MYSQL_ROOT_PASSWORD: password
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: redmine_crm_test
        POSTGRES_PASSWORD: password
